### ISSUE TITLE
Physic's range is permanently set at time of purchase

### ISSUE THREAD

**Issue by rayrobdod** [eliatlarge/FEMultiPlayer-V2#100]
Issue type: `problem`

#### Description:

In version 1.4.1:

In the team builder stage:

1. Select any unit (but to be most useful select a unit that can use staves and has high Mag growth)
2. Raise that unit to level 20.
3. Buy a Physic staff for that unit.
4. Lower the unit back to level 1.

The Physic will retain the range of the unit's Lv. 20 self, even though the unit is otherwise Level 1.

-------

#### Examples:

![Level 1 Erk (12 Mag) holding a 1-9 range Physic](https://cloud.githubusercontent.com/assets/11641215/15667124/83d97712-26e2-11e6-9d20-27b9fe42df58.png)
Note that a 12 Magic unit should have a Physic with range 1-6, and that Erk's Lv 20 Mag is 18.

![Level 1 Erk still has 9 range Physic in the field](https://cloud.githubusercontent.com/assets/11641215/15667244/43048af0-26e3-11e6-99a2-b7f2c5a7ab45.png)

**Comment by SapphireTactician** [comment]
Ew, good find. I can confirm this too. It seems like the range is only being calculated at the time of purchase. That means it retains its range even when traded. Physic's range needs to update whenever the owner or owner's stats change (*which occur can / will occur in more cases than just leveling - as the sub has been discussing introducing Brave Tomes and their FE Fates based side effect of temporarily reducing the user's Mag and Skl in order to prevent overshadowing legendary tomes*)

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #102 

Great job! @rayrobdod

**Comment by SapphireTactician** [comment]
Feel free to close as `Fixed` as per #102 . Won't let me do it myself.

Great job! @rayrobdod
