### ISSUE TITLE
Lethality shouldn't activate against Lords

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#44]
Issue type: `feature request`

#### Description:

As it stands, the Lethality skill works. However, an important catch to Lethality is that it's meant to never work on "boss units", which in FEMP would translate to Lords. It's description in all games that have it even say, "This skill is ineffective against certain units" As-is, Lethality in its current state is OP in matches with the Seize the Throne victory condition as the player loses if their lord falls.

I propose that we make Lethality more accurate in this respect by making it have a 0% activation rate against Lords.

-------

#### Reference:

http://fireemblem.wikia.com/wiki/Lethality

**Comment by SapphireTactician** [comment]
Requesting bug be reopened as Lethality still activated. Granted it missed (*perhaps due to Gamble being on*):

    [RCVE]2 COMMANDMESSAGE::Matthew move (0, 0):[EQUIP, Matthew, 0, ATTACK, Ephraim]
    [BATL]0 BATTLESTART::
    [BATL]0 HP::Matthew HP38 Ephraim HP31
    [BATL]0 ATTACKRECORD::Gamble(a) Miss: Matthew, Ephraim, 0, 0 (drain)
    [BATL]0 ATTACKRECORD::Gamble(a) Miss: Ephraim, Matthew, 0, 0 (drain)
    [BATL]0 ATTACKRECORD::Lethality(a) Miss: Matthew, Ephraim, 0, 0 (drain)
    [BATL]0 HP::Matthew HP38 Ephraim HP31
    [BATL]0 BATTLEEND::
    [SEND]2 COMMANDMESSAGE::Matthew move (0, 0):[EQUIP, Matthew, 0, ATTACK, Ephraim]

This was observed in the battle I did with myself yesterday when regression testing #83

**Comment by rayrobdod** [comment]
Skills have approximately three phases: the "did this activate?" phase, the stat-altering phase and the damage-modification phase. Eli's solution was to not touch the "did this activate" phase, but instead check the opponent's lordhood during the damage-modification phase and only increase damage dealt by 999 if the opponent is not a lord.

Had that attack hit, it should have done a normal amount of damage, just with the flashier effects. 

I do like my solution better, which modifies the "did this activate?" phase so that the flashy effects don't occur and don't confuse people into saying "Lethality activated! Why is the lord still standing?" I pushed it, but then didn't PR since Eli had already implemented his solution by then.

**Comment by SapphireTactician** [comment]
>I do like my solution better, which modifies the "did this activate?" phase so that the flashy effects don't occur and don't confuse people into saying "Lethality activated! Why is the lord still standing?"

You just read my mind, can we apply your solution? Otherwise, like you said, it'd just trigger confusion and look sloppy.

**Comment by eliatlarge** [comment]
Oh gosh, I didn't even realize that, I'm so sorry Ray. I'll just kinda pull your solution
